Vagrant.configure("2") do |config|
  config.vm.box = "test"

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.168.60.2"
  config.vm.define "test"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "test"
    vb.cpus = "1"
    vb.memory = "1048"
  end
end
