Vagrant.configure(2) do |config|

  config.vm.define "control-plane" do |node|

    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = "control-plane.cluster.com"
    node.vm.network "private_network", type: "dhcp"

    node.vm.provider "virtualbox" do |vb|
	  vb.name = "control-plane"
	  vb.cpus = 2
	  vb.memory = 2048
	end

  end

  NodeCount = 1

  (1..NodeCount) .each do |i|

    config.vm.define "worker#{i}" do |node|

      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "worker#{i}.cluster.com"
      node.vm.network "private_network", type: "dhcp"

      node.vm.provider "virtualbox" do |vb|
	    vb.name = "worker#{i}"
	    vb.cpus = 1
	    vb.memory = 1024
	  end

    end

  end

end
